import { Book, BookOpen, Palette, Pencil, Gamepad2, GraduationCap } from 'lucide-react';

export const categories = [
  { id: 1, name: 'Islamic Books', icon: Book, color: 'from-red-400 to-red-600', count: 1250 },
  { id: 2, name: 'General Books', icon: BookOpen, color: 'from-orange-400 to-red-500', count: 3420 },
  { id: 3, name: 'Art & Craft', icon: Palette, color: 'from-red-500 to-orange-600', count: 890 },
  { id: 4, name: 'Stationery', icon: Pencil, color: 'from-orange-500 to-amber-600', count: 2100 },
  { id: 5, name: 'Toys', icon: Gamepad2, color: 'from-red-500 to-pink-500', count: 650 },
  { id: 6, name: 'School Bundles', icon: GraduationCap, color: 'from-orange-600 to-red-600', count: 45 }
];

export const products = [
  { 
    id: 1, 
    name: 'Holy Quran with Translation', 
    price: 1500, 
    originalPrice: 1800,
    category: 'Islamic Books', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=300&h=300&fit=crop', 
    featured: true,
    rating: 4.9,
    reviews: 234,
    description: 'Beautiful hardcover edition with Arabic text and English translation',
    badge: 'Best Seller'
  },
  { 
    id: 2, 
    name: 'Oxford Advanced Dictionary', 
    price: 2500, 
    originalPrice: 2999,
    category: 'General Books', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop', 
    featured: false,
    rating: 4.7,
    reviews: 189,
    description: 'Comprehensive English dictionary for advanced learners'
  },
  { 
    id: 3, 
    name: 'Professional Watercolor Set', 
    price: 850, 
    originalPrice: 1200,
    category: 'Art & Craft', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=300&h=300&fit=crop', 
    featured: true,
    rating: 4.8,
    reviews: 156,
    description: '24 vibrant colors with premium brushes',
    badge: 'Limited Stock'
  },
  { 
    id: 4, 
    name: 'Premium Leather Notebook', 
    price: 450, 
    originalPrice: 550,
    category: 'Stationery', 
    inStock: false, 
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=300&fit=crop', 
    featured: false,
    rating: 4.6,
    reviews: 92,
    description: 'Handcrafted leather cover with premium paper'
  },
  { 
    id: 5, 
    name: 'STEM Building Blocks Set', 
    price: 1200, 
    originalPrice: 1500,
    category: 'Toys', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop', 
    featured: true,
    rating: 4.9,
    reviews: 312,
    description: 'Educational building blocks for creative learning',
    badge: 'Award Winner'
  },
  { 
    id: 6, 
    name: 'Islamic Stories Collection', 
    price: 650, 
    originalPrice: 850,
    category: 'Islamic Books', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1584286595398-a59511e0649f?w=300&h=300&fit=crop', 
    featured: false,
    rating: 4.8,
    reviews: 178,
    description: 'Inspiring stories from Islamic history for children'
  },
  { 
    id: 7, 
    name: 'Professional Sketch Pad A3', 
    price: 350, 
    originalPrice: 450,
    category: 'Art & Craft', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=300&h=300&fit=crop', 
    featured: false,
    rating: 4.5,
    reviews: 67,
    description: 'Heavy-weight paper perfect for sketching and drawing'
  },
  { 
    id: 8, 
    name: 'Scientific Calculator FX-991', 
    price: 1800, 
    originalPrice: 2200,
    category: 'Stationery', 
    inStock: true, 
    image: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=300&h=300&fit=crop', 
    featured: true,
    rating: 4.7,
    reviews: 423,
    description: 'Advanced scientific calculator for engineering students',
    badge: 'Top Rated'
  }
];

export const schoolBundles = [
  {
    id: 1,
    name: 'Grade 1 Complete Bundle',
    description: 'Everything your Grade 1 student needs for a successful academic year',
    grade: 'Grade 1',
    color: 'from-blue-400 to-blue-600',
    price: 3500,
    originalPrice: 4200,
    rating: 4.8,
    students: '2.3k',
    popular: true,
    items: [
      'Mathematics Workbook',
      'English Reading Books (Set of 5)',
      'Science Activity Kit',
      'Art & Craft Supplies',
      'Stationery Set (Pencils, Erasers, Colors)',
      'School Bag',
      'Water Bottle',
      'Lunch Box'
    ]
  },
  {
    id: 2,
    name: 'Grade 2 Essential Bundle',
    description: 'Comprehensive learning materials for Grade 2 students',
    grade: 'Grade 2',
    color: 'from-green-400 to-green-600',
    price: 3800,
    originalPrice: 4500,
    rating: 4.7,
    students: '1.9k',
    popular: false,
    items: [
      'Mathematics Textbook & Workbook',
      'English Grammar & Composition',
      'Science Experiment Kit',
      'Social Studies Atlas',
      'Drawing & Coloring Books',
      'Calculator (Basic)',
      'Geometry Set',
      'School Diary'
    ]
  },
  {
    id: 3,
    name: 'Grade 3 Advanced Bundle',
    description: 'Complete academic package for Grade 3 with enhanced learning tools',
    grade: 'Grade 3',
    color: 'from-purple-400 to-purple-600',
    price: 4200,
    originalPrice: 5000,
    rating: 4.9,
    students: '2.1k',
    popular: true,
    items: [
      'Core Subject Textbooks (Math, English, Science)',
      'Workbooks & Practice Books',
      'Educational Games & Puzzles',
      'Digital Learning Tablet',
      'Art Supplies Premium Set',
      'Sports Equipment (Basic)',
      'Study Lamp',
      'Bookshelf Organizer'
    ]
  },
  {
    id: 4,
    name: 'Grade 4 Scholar Bundle',
    description: 'Comprehensive learning package for Grade 4 academic excellence',
    grade: 'Grade 4',
    color: 'from-orange-400 to-orange-600',
    price: 4800,
    originalPrice: 5600,
    rating: 4.6,
    students: '1.7k',
    popular: false,
    items: [
      'Advanced Mathematics Kit',
      'Science Laboratory Set',
      'English Literature Collection',
      'History & Geography Books',
      'Computer Science Basics',
      'Musical Instruments (Recorder)',
      'PE Equipment Set',
      'Study Table & Chair'
    ]
  },
  {
    id: 5,
    name: 'Grade 5 Excellence Bundle',
    description: 'Complete preparation package for Grade 5 students',
    grade: 'Grade 5',
    color: 'from-red-400 to-red-600',
    price: 5200,
    originalPrice: 6200,
    rating: 4.8,
    students: '2.5k',
    popular: true,
    items: [
      'All Subject Textbooks & Guides',
      'Advanced Science Kit',
      'Mathematics Problem Solving Books',
      'English Advanced Grammar',
      'Computer Programming Basics',
      'Art & Design Portfolio',
      'Sports & Fitness Kit',
      'Study Desk Accessories',
      'Educational Software License'
    ]
  },
  {
    id: 6,
    name: 'Middle School Starter Bundle',
    description: 'Transition package for students moving to middle school',
    grade: 'Grade 6',
    color: 'from-teal-400 to-teal-600',
    price: 5800,
    originalPrice: 6800,
    rating: 4.7,
    students: '1.4k',
    popular: false,
    items: [
      'Middle School Textbook Set',
      'Scientific Calculator',
      'Laboratory Equipment Kit',
      'Language Learning Materials',
      'Project Presentation Kit',
      'Leadership & Life Skills Books',
      'Technology & Coding Starter Kit',
      'Premium Stationery Set'
    ]
  }
];

export const stores = [
  {
    id: 1,
    name: 'Booktime Gulberg',
    type: 'Flagship Store',
    address: 'Main Market, Gulberg III',
    city: 'Lahore',
    area: 'Gulberg',
    phone: '+92 42 35757575',
    hours: '9:00 AM - 10:00 PM',
    status: 'Open',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
    distance: '2.3 km',
    services: ['Same Day Delivery', 'Gift Wrapping', 'Book Binding', 'Student Discounts']
  },
  {
    id: 2,
    name: 'Booktime DHA',
    type: 'Premium Store',
    address: 'Y Block Commercial, DHA Phase III',
    city: 'Lahore',
    area: 'DHA',
    phone: '+92 42 35858585',
    hours: '10:00 AM - 9:00 PM',
    status: 'Open',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    distance: '4.1 km',
    services: ['Express Pickup', 'VIP Lounge', 'Coffee Corner', 'Kids Play Area']
  },
  {
    id: 3,
    name: 'Booktime Fortress',
    type: 'Mall Store',
    address: 'Fortress Stadium, Cantt',
    city: 'Lahore',
    area: 'Cantt',
    phone: '+92 42 35959595',
    hours: '11:00 AM - 11:00 PM',
    status: 'Open',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=400&h=300&fit=crop',
    distance: '6.8 km',
    services: ['Mall Delivery', 'Gift Vouchers', 'School Partnerships', 'Bulk Orders']
  },
  {
    id: 4,
    name: 'Booktime Packages Mall',
    type: 'Shopping Center',
    address: 'Packages Mall, Walton Road',
    city: 'Lahore',
    area: 'Walton',
    phone: '+92 42 36060606',
    hours: '11:00 AM - 12:00 AM',
    status: 'Open',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop',
    distance: '8.2 km',
    services: ['Food Court Access', 'Gaming Zone', 'Study Areas', 'Event Hosting']
  },
  {
    id: 5,
    name: 'Booktime F-7',
    type: 'Branch Store',
    address: 'Jinnah Super Market, F-7 Markaz',
    city: 'Islamabad',
    area: 'F-7',
    phone: '+92 51 26262626',
    hours: '9:30 AM - 9:30 PM',
    status: 'Open',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1519327232521-1ea2c736d34d?w=400&h=300&fit=crop',
    distance: '1.5 km',
    services: ['Government Sector Discounts', 'Home Delivery', 'Corporate Orders']
  },
  {
    id: 6,
    name: 'Booktime Blue Area',
    type: 'Corporate Store',
    address: 'Jinnah Avenue, Blue Area',
    city: 'Islamabad',
    area: 'Blue Area',
    phone: '+92 51 27272727',
    hours: '8:00 AM - 8:00 PM',
    status: 'Closed',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=400&h=300&fit=crop',
    distance: '3.7 km',
    services: ['Business Hours Only', 'Corporate Accounts', 'Bulk Educational Materials']
  },
  {
    id: 7,
    name: 'Booktime Clifton',
    type: 'Flagship Store',
    address: 'Main Clifton Road, Block 2',
    city: 'Karachi',
    area: 'Clifton',
    phone: '+92 21 35353535',
    hours: '10:00 AM - 10:00 PM',
    status: 'Open',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=300&fit=crop',
    distance: '5.3 km',
    services: ['Beach View Cafe', 'Author Meetups', 'Reading Clubs', 'Cultural Events']
  },
  {
    id: 8,
    name: 'Booktime Dolmen Mall',
    type: 'Mall Store',
    address: 'Dolmen City Mall, Clifton',
    city: 'Karachi',
    area: 'Clifton',
    phone: '+92 21 36464646',
    hours: '12:00 PM - 12:00 AM',
    status: 'Open',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1495344517868-8ebaf0a2044a?w=400&h=300&fit=crop',
    distance: '7.9 km',
    services: ['Late Night Shopping', 'Entertainment Zone', 'Food Court Access', 'Parking']
  }
]; 